FROM node:14-alpine
ARG APPLICATION_PATH=/app
ARG FIREBASE_CONFIG
ARG GRAPHQL_URL
ARG SENTRY_DSN
ARG APP_ENV
WORKDIR ${APPLICATION_PATH}
COPY . ${APPLICATION_PATH}
COPY .nuxt ${APPLICATION_PATH}/.nuxt
RUN yarn add @nuxtjs/sentry
EXPOSE 3000 
ENTRYPOINT yarn start 
